### ISSUE TITLE
auto-mesh should exlcude terminating pods

### ISSUE THREAD

**Issue by grs** [interconnectedcloud/qdr-image#12]
At present the 'query' mode of automesh looks for pods in the router deployment and based on timestamp, determines connectors at start up time to ensure a full mesh. However it does not exclude pods in the terminating state which leads to unnecessary 'dangling' connectors.

Though connectors to stale pods can't be completely avoided with the query mode (and they are mostly harmless), it would be a useful improvement to exclude pods in the terminating state.

**Comment by grs** [comment]
I think this can be solved in scripts/auto_mesh.py by checking that ```'deletionTimestamp' not in pod``` before adding to the pod list

**Comment by ganeshmurthy** [comment]
Fixed via commit 07890e3342ba1c7e89754cb79f2facbcdbad151d
